# numpy

NumPy is a Python library for multi-dimensional arrays and matrices and associated mathematical functions. We will use NumPy a little bit so we'll cover the basics here. A fuller tutorial [can be found here](https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html).

First we import numpy. This is commonly done as follows so that we can refer to the numpy functions with np later.

In [1]:
import numpy as np

### arrays

NumPy arrays are similar to lists in Python but every element has to be of the same type. This data type is designed to allow for very fast computations. The following creates a NumPy array out of a Python list and makes each element a float. 

The function **array** takes two arguments: the list to be converted and the type. Array elements can be indexed and sliced the same as Python lists. 



In [2]:
a = np.array([1,2,3,4,5], float)
print(a)
print(a[2])


[1. 2. 3. 4. 5.]
3.0


### array terminology

NumPy arrays can be multidimensional. The dimensions are called *axes* and the number of axes is the *rank*. Notice that we have brackets within brackets to specify the rows of the 2D array. 

In [3]:
b = np.array([[1,2,3], [4,5,6]], int)
print(b)
b[1,1]

[[1 2 3]
 [4 5 6]]


5

### shape

We can also reshape arrays with *reshape*. And we can get the dimensions with the *shape* attribute. However, *len* returns the length of the first axis.

In [4]:
c = np.array(range(10), float)
print("c originally: ", c)
c = c.reshape(5, 2)
print("c with the new shape: \n", c)
print("The new shape is: ", c.shape)
print("Length = ", len(c))

c originally:  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
c with the new shape: 
 [[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
The new shape is:  (5, 2)
Length =  5


### initializing an array

We can fill an array with a value as shown below for initialization or re-initialization with **fill** or create a new zero array with **zeros**.


In [5]:
c.fill(0)
print("c is now all 0s:\n", c)

d = np.zeros( (2,3))
d

c is now all 0s:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.]])

Yet another way to create an array is with **arange**. There are many other functions to create, rearrange and modify arrays but we are just covering the basics here.

In [6]:
e = np.arange(8, dtype=int)
e

array([0, 1, 2, 3, 4, 5, 6, 7])

### Math functions

Operations like + and - operate on an element-by-element basis as you would expect. An error will be thrown in the sizes do not match the operation.

There are also mathematical functions like sqrt, log, sin and so forth that are also applied element by element.

These two constants are also provided: **np.pi** and **np.e**

Other functions such as sum, prod, mean, var std operate on the array as a whole.



In [7]:
print("sum=", np.sum(e))
print("average=", np.mean(e))
print("min=", np.min(e))

sum= 28
average= 3.5
min= 0


You can also specify an axis on which to perform the operation, with different syntax. It will return an array with results. 

In [8]:
f = np.array(range(10), float).reshape(5,2)
print(f)
f.mean(axis=0)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


array([4., 5.])

### boolean selection

The following returns an array of indices for elements that mean the boolean criteria. 

In [9]:
i = (e >= 5)
e[i]

array([5, 6, 7])

### sort an array

In [10]:
sorted(e, reverse=True)

[7, 6, 5, 4, 3, 2, 1, 0]

### vector and matrix operations

The **dot** function computes dot  products for vectors or matrices.

In [11]:
v1 = np.array([1,2,3], float)
v2 = np.array([4, 5, 6], float)
np.dot(v1, v2)

32.0

In [12]:
m1 = np.array([[0, 1], [2, 3]], float)
m2 = np.array([4, 5], float)
np.dot(m2, m1)

array([10., 19.])

There are also matrix operations for inverse, determinant, eigenvalues and eigenvectors and singular value decomposition. 

### random numbers

Randome numbers and arrays of random numbers can be generated. You can specify normal, poisson and other distributions. 

In [13]:
np.random.seed(42)
np.random.rand(2,3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [14]:

np.random.shuffle(e)
e

array([0, 1, 6, 5, 3, 4, 7, 2])