# Converting text to numeric data

Machine learning algorithms learn from numeric data. In order for the algorithms to learn from text, the text has to be represented in some numerical form. One way to do this is to represent documents as vectors of frequencies, where each location in the vector represents the count of a specific word in that document. To demonstrate this, a toy corpus is created from text.

In [3]:
corpus = ['Mary had a little lamb.',
         'The lamb followed Mary to school one day.',
         'The lamb was white.',
         'Mary should not bring a lamb to school.',
         'Mary is a little rebel.']

### CountVectorizer

The sklearn CountVectorizer function:
* tokenizes the text
* assigns a unique integer id to each word in the corpus
* counts the frequencies for each word

The code below first creates a CountVectorizer instance, then fits the corpus.

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(corpus)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

The output above shows the default options for CountVectorizer. Full descriptions of each parameter are provided in the documentation.

Next, corpus counts and names are extracted from the vectorizer fit.

In [5]:
corpus_counts = vectorizer.fit_transform(corpus)
print(corpus_counts.toarray())
print('names:', vectorizer.get_feature_names())

[[0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 1 0 1 0 1 0 1 0 1 1 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1]
 [1 0 0 0 0 1 0 1 1 0 0 1 1 0 1 0 0]
 [0 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0]]
names: ['bring', 'day', 'followed', 'had', 'is', 'lamb', 'little', 'mary', 'not', 'one', 'rebel', 'school', 'should', 'the', 'to', 'was', 'white']


In the 2D array above, each row represents one document in the corpus and each column represents a word. Each element represents the count of that word in that document. As you can see, most counts are zero. These types of vectorized representations of a corpus produce a sparse matrix.

### TfidfVectorizer

The code below shows how to use the TfidfVectorizer which produces tfidf values instead of frequency counts.

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [8]:
# take a look at  the terms and idf
print('terms:', vectorizer.vocabulary_)
print('\nidf:', vectorizer.idf_)

terms: {'mary': 7, 'had': 3, 'little': 6, 'lamb': 5, 'the': 13, 'followed': 2, 'to': 14, 'school': 11, 'one': 9, 'day': 1, 'was': 15, 'white': 16, 'should': 12, 'not': 8, 'bring': 0, 'is': 4, 'rebel': 10}

idf: [2.09861229 2.09861229 2.09861229 2.09861229 2.09861229 1.18232156
 1.69314718 1.18232156 2.09861229 2.09861229 2.09861229 1.69314718
 2.09861229 1.69314718 1.69314718 2.09861229 2.09861229]


## Isolating the test data

The previous examples showed how to apply the vectorizers to the entire corpus. For supervised machine learning, a better approach is to first divide the data into train/test sets, then fit the vectorizer to the training data only. The test set can be later fit to the vectorizer. In this way, no information from the test set leaks to the training set. The following code demonstrates how to do this on a hypothetical data set.